Add 10.0 delivery carrier label seur
OCA/delivery-carrier pull request #127
Opened 2017-04-11 13:55 UTC by angelmoya

Check before:

#124

2017-12-12 15:35 UTC, jesusVMayor requested changes

2017-12-12 15:35 UTC, jesusVMayor commented on delivery_carrier_label_seur/model/stock.py
> +        if not self.carrier_id or self.carrier_id.type != 'seur':
this must be self.carrier_id.carrier_type != 'seur'

2018-04-12 09:51 UTC, rafaelbn commented
Hi @angelmoya , could you take a look here please? Are you using this module in customer's production instance? Thanks! :smile:

2018-04-12 09:57 UTC, angelmoya commented
Hi @rafaelbn I'm not using on production, this PR has one year, and I did in colaboration with customer that auto implant odoo.... so I don't support this now.

@jesusVMayor please, create new PR with this changes.

2018-04-13 23:12 UTC, rafaelbn commented
OK @angelmoya . Please could you at least rebase this PR as https://github.com/OCA/delivery-carrier/pull/124 was merged yo see if bots go green? Thanks!

2018-09-19 21:38 UTC, closed without merging