[10.0] migrate delivery_carrier_label postlogistics
OCA/delivery-carrier pull request #128
Opened 2017-04-20 16:34 UTC by yvaucher

cherry pick of commits from 9.0

+

* Simplify signature of soap connector by removing company
* As carrier inherits from product, change postlogistics partner as
  a service product

Specific changes to v 10.0 are in https://github.com/yvaucher/carrier-delivery/commit/abfa3395b1666f41b7673f4f24d8878a6e5f2dd3

2017-11-27 15:40 UTC, grindtildeath commented on delivery_carrier_label_postlogistics/models/delivery.py
> +                        "[('product_id', '=', %s), "
There is no `product_id` on `delivery.carrier.template.option` model, what brings :
```
ValueError: Invalid field u'product_id' in leaf "<osv.ExtendedLeaf: (u'product_id', u'=', 2) on delivery_carrier_template_option (ctx: )>"
```

2018-05-29 08:17 UTC, gurneyalex approved these changes

2018-05-29 09:12 UTC, simahawk requested changes
small things

2018-05-29 09:12 UTC, simahawk commented on delivery_carrier_label_postlogistics/__manifest__.py
>   'website': 'http://www.camptocamp.com/',
ttps://github.com/OCA/delivery-carrier

2018-05-29 09:12 UTC, simahawk commented on delivery_carrier_label_postlogistics/data/partner.xml
> +  <record id="partner_postlogistics" model="res.partner">
noupdate?

2018-05-29 09:12 UTC, simahawk commented on delivery_carrier_label_postlogistics/models/company.py
> +        path = 'delivery_carrier_label_postlogistics/data/'
would be better to use `from odoo.modules.module import get_resource_path`

2018-05-29 09:12 UTC, simahawk commented on delivery_carrier_label_postlogistics/README.rst
>  https://pypi.python.org/pypi/suds-jurko/0.6
can you update whole readme based on new layout? https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

2018-05-29 10:09 UTC, grindtildeath commented
@simahawk Fixed, and squashed my last commits. I left @yvaucher 's as they are.

2018-05-29 14:02 UTC, simahawk approved these changes

2018-05-30 10:40 UTC, simahawk commented
@grindtildeath once you fix this warning on runbot we should be able to merge /cc @gurneyalex 
```
2018-05-29 11:16:29,382 182 WARNING openerp_test odoo.addons.base.module.module: module delivery_carrier_label_postlogistics: description is empty !
```

2018-05-30 12:11 UTC, grindtildeath commented
@simahawk Shouldn't we backport this commit ? https://github.com/OCA/delivery-carrier/pull/155/commits/d9e681215e0a3f1739eaca495f7f2ceaa7ba6d96

2018-05-30 12:56 UTC, simahawk commented
@grindtildeath I'd say "yes". See my comments on it ;)

2018-06-26 11:24 UTC, merged