[10.0][MIG] sale_delivery_rate
OCA/delivery-carrier pull request #135
Opened 2017-05-26 00:27 UTC by bmw95

Hi there,

Migration of sale_delivery_rate from 9.0 to 10.0.

Cheers,
Brett

@lasley @obulkin

2017-05-26 01:01 UTC, bmw95 commented
Runbot is failing because of model.access rules on a transient model in base_delivery_carrier_label [here](https://github.com/OCA/delivery-carrier/blob/10.0/base_delivery_carrier_label/security/ir.model.access.csv#L13). (line 14 as well). Should those be removed from that module?

Other than that, ready for review!

2017-05-26 01:23 UTC, lasley commented
@bmw95 we can ignore the Runbot warning here, because it is also failing for the same thing on v10. Might as well submit a quick PR though to fix now that you've investigated

2017-05-26 01:25 UTC, lasley approved these changes
Thanks @bmw95

2017-05-26 01:32 UTC, bmw95 commented
base_delivery_carrier_label security fix has been submitted in #136

2017-06-16 20:40 UTC, bmw95 commented
nice this is good to go. Rebased to 10.0 now that #136 is merged.

2017-06-20 17:08 UTC, lasley commented
@obulkin please review

2017-06-20 21:27 UTC, obulkin requested changes

2017-06-20 21:27 UTC, obulkin commented on sale_delivery_rate/models/delivery_carrier_rate.py
> +            for record_data in recordset_data:
There's no need for an inner loop here now that you're calling `copy_data` against a single record. The result will be a single dictionary inside a list, so you can just do `record_data = record.copy_data()[0]` instead.

2017-06-22 00:15 UTC, bmw95 commented on sale_delivery_rate/models/delivery_carrier_rate.py
> +            for record_data in recordset_data:
oh yeah weird. Didn't catch that while upgrading, thanks!

2017-06-22 00:29 UTC, bmw95 commented on sale_delivery_rate/models/delivery_carrier_rate.py
> +            for record_data in recordset_data:
Hmm. Actually no this is correct. The code is ensuring the arg is a singleton: `stock_picking.ensure_one()`not `self.ensure_one()`. I think I remember coming across this earlier. Removing the loop causes multiple records to be copied at a time.

2017-06-22 00:36 UTC, bmw95 commented on sale_delivery_rate/models/delivery_carrier_rate.py
> +            for record_data in recordset_data:
oh got it I misunderstood. don't need to loop through the record_data. For some reason I was thinking "don't loop through the records . . ."

2017-06-22 02:52 UTC, obulkin approved these changes

2017-06-24 01:15 UTC, merged