[FIX] carrier type is not the same that delivery type
OCA/delivery-carrier pull request #199
Opened 2019-05-29 07:29 UTC by angelmoya

In OCA Sprint Code we was checking the migration to versión 12.0, and we think that it was a mistake in migration to version 11.0.

In version 10.0 we  have carrier_type field, it define the carrier company, and how to comunicate to send data and get labels.

In versión 11.0 we have delivery_type field, it define how to compute prices, it not the same scope.

In #155 we check that postlogistic is added to delivery_type, but I think that could be better if you can define postlogistic in carrier_type and delivery_type regardless.

It is usual to have delivery method with diferent sale price than purchase price, so if you habe two fields you can send data to your carrier but mantain fixed prices.

2019-05-29 07:30 UTC, angelmoya commented
@jctrey

2019-05-29 07:31 UTC, pedrobaeza commented
I agree with this approach

2019-05-29 07:37 UTC, jctrey commented
Much better, why not create a base module for all delivery carrier functionalities as label and tracking link, instead of define the commented field in "base_delivery_carrier_label" module.

2019-05-29 07:52 UTC, grindtildeath requested changes
"In versión 11.0 we have delivery_type field, it define how to compute prices, it not the same scope."

Sorry, but this is wrong: https://github.com/odoo/odoo/blob/11.0/addons/delivery/models/delivery_carrier.py#L22

Price computation should be done using `rate_shipment` as explained in the official module.

We changed this to 11.0 since we didn't want to interfere with what was already existing in 10.0, but in no way should we revert to this.

2019-05-29 08:05 UTC, angelmoya commented
This way you can not create delivery method free of charge with delivery company to send parcel and get labels.

2019-05-29 08:06 UTC, jctrey commented
@grindtildeath you're right "Price computation should be done using rate_shipment as explained in the official module." but the suggested field will be very useful for other purposes, as detect the way an specific carrier (as FedEx, UPS, ...) will compose tracking urls and so on regardless of the price calculation method wich will be shared by many carriers.

2019-05-29 08:35 UTC, grindtildeath commented
@angelmoya @jctrey 
But why would you need to hijack an existing field with a well defined purpose instead of defining another field with a clear purpose as well ? I don't get it...

2019-05-29 09:00 UTC, jctrey commented
@grindtildeath yes, I think that's the perfect solution, to create a new field, problem solved

2019-06-06 14:32 UTC, rafaelbn commented
@angelmoya thank! can you make bots :green_apple: ? :smile:

2019-06-06 16:43 UTC, angelmoya commented
We can cancel that, we will use other field.

2019-06-06 16:43 UTC, closed without merging