[MIG] port delivery_carrier_label_default to V10
OCA/delivery-carrier pull request #207
Opened 2019-07-17 08:05 UTC by thomaspaulb

Replaces https://github.com/OCA/delivery-carrier/pull/186

2019-07-18 14:18 UTC, thomaspaulb commented
@pedrobaeza Could you help me here also? I don't see any warnings in runbot here, it looks like some kind of timeout.

2019-07-19 08:13 UTC, pedrobaeza commented
It seems all the builds are stuck. This is probably a failed tests + the use of any printing, as the way wkhtmltopdf opens connections hangs threads in these conditions.

2019-11-12 15:08 UTC, thomaspaulb commented
@pedrobaeza I managed to reproduce this condition on my local. The test generates a report, during which wkhtmltopdf tries to download CSS files from http://localhost:8069, and this request does not complete. Even running `wget http://localhost:8069/web` in parallel does not complete.

I failed to see this before because in my local, I usually run tests with `--xmlrpc-port=18079`, in which case the request _does_ complete and all three tests run successfully. However, on further inspection this is because the base URL of Odoo in the report HTML is still set to port 8069, so it goes through, but without loading the CSS. Not a problem for this test, but also not a real solution.

Do you have any idea why requests to Odoo don't complete during the test, and how to solve this?

2019-11-12 15:28 UTC, pedrobaeza commented
It's because HttpCase tests create a new cursor and there's a DB lock without releasing it when there's an error in a previous tests. It shouldn't happen if all goes right, but with any problem you will get to that stuck situation.

2019-11-13 15:58 UTC, thomaspaulb commented
@pedrobaeza But if that is true, shouldn't I see the error in the previous tests in the log? It's now green upon using the other port - if your explanation holds, it should be red.

2019-11-13 15:59 UTC, pedrobaeza commented
Well, I'm telling you my previous experiences, but @moylop260 knows better the internals of this.

2019-11-22 21:20 UTC, moylop260 commented
Hi @thomaspaulb 

Let me try to explain it since that it a matter so complex for me.

The method `generate_default_label` of `delivery_carrier_label_default/models/stock.py` file has the following code:
 - `pdf_report = self.env['report'].get_pdf([self.id], 'delivery_carrier_label_default.report_default_label')`

It run a `wkhtmltopdf` command that requires get data from the self-instance but externally.
I mean, accessing from external requests.

So it transform your odoo.tests.TransactionCase (back-end) to odoo.tests.HttpCase (front-end) where it requires that odoo instance is running finally (not loading yet).

You can see the following wkhtmltopdf freeze command waiting for instance finish of load, but it is waiting for wkhtmltopdf at the same time.
 - ![wkhtmltopdf_error](https://user-images.githubusercontent.com/6644187/69460378-9b6b0300-0d39-11ea-94c2-cd841191c625.gif)


Now, let's try using HttpCase where the tests is running after instance is entirely loaded:
 - ![httpcase](https://user-images.githubusercontent.com/6644187/69461010-20a2e780-0d3b-11ea-8e69-ea3f46a3e345.gif)

Conclusion your final patch should be:

```patch
diff --git a/delivery_carrier_label_default/tests/test_print_label.py b/delivery_carrier_label_default/tests/test_print_label.py
index 6fc34c8..71fac46 100644
--- a/delivery_carrier_label_default/tests/test_print_label.py
+++ b/delivery_carrier_label_default/tests/test_print_label.py
@@ -1,10 +1,10 @@
 # -*- coding: utf-8 -*-
 # © 2016 Sunflower IT (http://sunflowerweb.nl)
 # License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
-from odoo.tests.common import TransactionCase
+from odoo.tests.common import HttpCase


-class TestPrintLabel(TransactionCase):
+class TestPrintLabel(HttpCase):

     def test_print_default_label(self):
         self.picking.generate_labels()
```

2019-11-22 22:14 UTC, moylop260 commented
About using another port the issue is that it parameter is used just for second time of the command `odoo-bin`

I mean,
First time the default port is `8069`:
 - https://travis-ci.org/OCA/delivery-carrier/jobs/610902351#L524

So the database configuration parameters are stored using 8069 by default.

The second time the port is changed to `18079`
 - https://travis-ci.org/OCA/delivery-carrier/jobs/610902351#L1048
but configuration parameters are still stored using 8069

So  you won't have a freeze here since that the requests were refused but wkhtmltopdf error is muted.
You can see the following image using 18079 port for second odoo-bin command:
 - ![Screen Shot 2019-11-22 at 15 56 25](https://user-images.githubusercontent.com/6644187/69464113-14228d00-0d43-11ea-835a-87b23b30dc08.png)

Notice a `ConnectionRefusedError` in `wkthmltopdf` but without a raise for odoo.

2019-11-22 22:20 UTC, moylop260 commented
Maybe you are interested to see the old thread about:
 - https://github.com/OCA/maintainer-quality-tools/issues/509

2019-11-24 09:24 UTC, thomaspaulb commented
@moylop260 Thank you so much for this detailed explanation, very clear.

2019-11-24 16:53 UTC, moylop260 approved these changes
👍 
Technical review (no functional tests)

2019-11-25 21:16 UTC, rousseldenis requested changes
Code review

2019-11-25 21:16 UTC, rousseldenis commented on delivery_carrier_label_default/models/stock.py
> -# Copyright 2013-2016 Camptocamp SA
You cannot remove exisitng author. Just add yourself to exisitng (new line)

2019-11-25 21:16 UTC, rousseldenis commented on delivery_carrier_label_default/__manifest__.py
> +# © 2016 Sunflower IT (http://sunflowerweb.nl)
Please add here original author.

2019-11-25 21:16 UTC, rousseldenis commented on delivery_carrier_label_default/__manifest__.py
> + 'maintainer': 'Sunflower IT',
s/maintainer/maintainers and value as list()

And please follow https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py

2019-11-25 21:16 UTC, rousseldenis commented on delivery_carrier_label_default/__manifest__.py
> + 'category': 'Delivery',
Please change this to 'Warehouse' or it does not appear in godd category in OCA shop.

2019-11-25 21:16 UTC, rousseldenis commented on delivery_carrier_label_default/tests/test_print_label.py
> -# Copyright 2016 Camptocamp SA
Same as above

2019-11-26 14:03 UTC, thomaspaulb commented
@rousseldenis Thanks, did the fixes

2019-11-26 15:50 UTC, rousseldenis commented
Seems ok, could you squash your commits ?

2021-12-19 21:38 UTC, thomaspaulb commented
@rousseldenis If you give your final approval here, we can get this merged.

2021-12-20 06:25 UTC, rousseldenis approved these changes

2021-12-20 06:26 UTC, rousseldenis commented
/ocabot merge patch

2021-12-20 06:41 UTC, merged