[MIG][12.0] delivery carrier partner
OCA/delivery-carrier pull request #221
Opened 2019-09-05 14:59 UTC by ValentinVinagre

Standard Migration.
cc @sygel-technology

2019-09-05 15:17 UTC, HaraldPanten approved these changes
Tested on runbot 👍

2019-10-28 13:36 UTC, rousseldenis requested changes
Code review. Minor comment

2019-10-28 13:36 UTC, rousseldenis commented on delivery_carrier_partner/__manifest__.py
> +    "category": "Delivery",
Please set to 'Warehouse' as it would appear in wrong category on OCA shop

2020-01-10 10:52 UTC, gurneyalex commented on delivery_carrier_partner/__manifest__.py
> +    "category": "Delivery",
```suggestion
    "category": "Warehouse",
```

2020-01-10 10:57 UTC, merged