[IMP] partner_delivery_schedule: Remove badge class to recovery font size
OCA/delivery-carrier pull request #250
Opened 2020-02-04 17:58 UTC by sergio-teruel

cc @Tecnativa TT21941
@Tardo  @manuelcalerosolis  REview please...

2020-02-05 13:50 UTC, Tardo reviewed
You can use `$badge-font-size` and `$badge-font-weight` to control this...
BUT if you don't want change css, please, add a comment to know why this badges don't follow the bootstrap documentation.

2020-02-17 21:00 UTC, sergio-teruel commented
Ok @Tardo Changes done!

2020-02-18 19:18 UTC, Tardo commented
Please, check travis.

2020-02-18 19:35 UTC, Tardo requested changes

2020-02-18 19:35 UTC, Tardo commented on partner_delivery_schedule/views/report_shipping.xml
> +        <xpath expr="//div[@class='page']" position="inside">
```suggestion
        <xpath expr="//div[hasclass('page')]" position="inside">
```

2020-02-18 19:35 UTC, Tardo commented on partner_delivery_schedule/views/report_shipping.xml
> +        <xpath expr="//div[@class='page']" position="inside">
```suggestion
        <xpath expr="//div[hasclass('page')]" position="inside">
```

2020-02-18 21:24 UTC, sergio-teruel commented
@Tardo Done!!

2020-02-21 20:23 UTC, Tardo approved these changes

2020-02-21 21:07 UTC, pedrobaeza approved these changes

2020-02-21 21:07 UTC, pedrobaeza commented
/ocabot merge minor

2020-02-21 21:15 UTC, merged