[FIX] delivery_carrier_label_postlogistic char encoding
OCA/delivery-carrier pull request #309
Opened 2020-10-23 11:12 UTC by gurneyalex

It seems Postlogistics REST web service is unhappy with the normal JSON encoding
of non ASCII characters and requires these to be encoded in utf-8 -> by using ensure_ascii=False in the call to json.dumps() we try obtain this. 

From the `json` documentation:

    If `ensure_ascii` is false, then the return value can contain non-ASCII
    characters if they appear in strings contained in `obj`. Otherwise, all
    such characters are escaped in JSON strings.

2020-10-23 11:12 UTC, gurneyalex commented
This is an alternate fix for the issue that #301 tries to tackle.

2020-10-26 16:23 UTC, yvaucher commented
Testing it I get this answer from the API:

> Error when communicating with swisspost API: [ {
> "error" : "InvalidJSON"
> } ]

2020-10-26 16:24 UTC, yvaucher requested changes
doesn't seems to do the trick, ~~ #301 will be the way to go ~~

we are just missing an encoding.

2020-10-27 13:25 UTC, yvaucher commented
The API seemingly just had an update that makes this fix obsolete.

2020-10-27 13:25 UTC, closed without merging