[13.0] [MIG] delivery_multi_destination: Migration to v13.0
OCA/delivery-carrier pull request #329
Opened 2021-01-26 13:27 UTC by CarlosRoca13

cc @Tecnativa TT26765

please @pedrobaeza @ernestotejeda review this

2021-01-26 18:00 UTC, ernestotejeda reviewed
Code review :+1:

2021-01-26 19:15 UTC, pedrobaeza requested changes

2021-01-26 19:15 UTC, pedrobaeza commented on delivery_multi_destination/tests/test_delivery_multi_destination.py
> +        )
You should search by `is_delivery` flag, and the search is not limited by the order, so it's searching globally:
```suggestion
        sale_order_line = order.order_line.filtered("is_delivery")
```
do the same on the rest

2021-01-27 07:17 UTC, CarlosRoca13 commented
@pedrobaeza changes done

2021-01-27 07:54 UTC, pedrobaeza approved these changes

2021-01-27 07:54 UTC, pedrobaeza commented
/ocabot merge nobump

2021-01-27 08:07 UTC, merged