[13.0][ADD] connector_routific: New module for connect with Routific Platform
OCA/delivery-carrier pull request #353
Opened 2021-04-08 08:49 UTC by CarlosRoca13

cc @Tecnativa TT28665

With this module we allow to connect Odoo with Routific for manage the route optimization.

please @carlosdauden @sergio-teruel review this

2021-04-08 09:05 UTC, chienandalu requested changes
Tests aren't working in travis

2021-06-09 07:07 UTC, pedrobaeza requested changes

2021-06-09 07:07 UTC, pedrobaeza commented on connector_routific/security/res_groups.xml
> +    <record id="group_routific_manager" model="res.groups">
Why creating a specific group for this and not binding it to an existing one? And now you will need `sudo` in all the operations that needs this data.

2021-08-09 11:29 UTC, chienandalu approved these changes
Minor comment

2021-08-09 11:29 UTC, chienandalu commented on connector_routific/__manifest__.py
> +    "development_status": "Alpha",
This should change to stable as it's working on customer for a couple of months already, isn't it?

2021-08-12 06:15 UTC, CarlosRoca13 commented
Changed @chienandalu

2022-05-30 08:01 UTC, sergio-teruel approved these changes

2022-05-30 08:01 UTC, sergio-teruel commented
Can we merge this PR?

2022-05-30 08:03 UTC, pedrobaeza approved these changes

2022-05-30 08:03 UTC, pedrobaeza commented
/ocabot merge nobump

2022-05-30 08:13 UTC, merged