[14.0][ADD] delivery_carrier_agency
OCA/delivery-carrier pull request #384
Opened 2021-06-21 13:37 UTC by florian-dacosta

It is a small module, that does not do much by itself.
It add the concept of carrier agency.
This module could be usefull for label generation for some carrier for instance.
Indeed, some carrier (like GEODIS) need the information of which agency will receive the package when generating the delivery labels.
For instance if you have one warehouse in north of France and another in south, the carrier agency that will handle the packages will be different.

So this module add the model of carrier agency and a helper to find the right agency of a carrier.

@hparfr

2021-06-21 15:04 UTC, hparfr requested changes

2021-06-21 15:04 UTC, hparfr commented on delivery_carrier_agency/readme/DESCRIPTION.rst
> +A delivery carriere may have one or mutliple agencies.
```suggestion
A delivery carrier may have one or multiple agencies.
```

2021-06-21 15:04 UTC, hparfr commented on delivery_carrier_agency/models/delivery_carrier_agency.py
> +    code = fields.Char()
```suggestion
    external_reference = fields.Char(help="Reference or code supplied by the carrier")
```

2021-06-21 15:04 UTC, hparfr commented on delivery_carrier_agency/models/delivery_carrier_agency.py
> +    _description = "Carrier Agency"
add a sequence or an order_by

2021-06-21 15:04 UTC, hparfr commented on delivery_carrier_agency/readme/DESCRIPTION.rst
> +Add carrier agencies concept
```suggestion
Add carrier agency concept
```

2021-06-21 18:07 UTC, florian-dacosta commented on delivery_carrier_agency/readme/DESCRIPTION.rst
> +Add carrier agencies concept
thx for the review, I've made all the changes

2021-06-22 06:54 UTC, hparfr approved these changes
LGTM

2021-07-12 23:11 UTC, sebastienbeau approved these changes
LGTM (code review)

2021-07-13 07:30 UTC, hparfr commented
/ocabot merge nobump

2021-12-04 13:49 UTC, dreispt commented
/ocabot merge nobump

2021-12-04 14:10 UTC, merged