14.0 mig delivery carrier label default
OCA/delivery-carrier pull request #396
Opened 2021-07-17 23:03 UTC by KKamaa

migration to v14.0 see sample below
![delivery-carrier](https://user-images.githubusercontent.com/10249832/126051147-8aed0478-5aef-4fb0-bd63-5cfc167d7eac.gif)

2021-11-23 12:58 UTC, gfcapalbo requested changes
Multi Decorator is deprecated in v14, please remove, 
the rest looks consistent with the last known version on v11.
I see no differences in the report.render method, so it should work the same.

Approved after decorator removal.

2021-11-23 12:58 UTC, gfcapalbo commented on delivery_carrier_label_default/models/stock_picking.py
> +    @api.multi
multi is deprecated in 14.0 remove or will gen error

2021-11-23 13:06 UTC, gfcapalbo requested changes

2021-11-23 13:06 UTC, gfcapalbo commented on delivery_carrier_label_default/__manifest__.py
> +        "stock",
redundant, it is already installed via the dependency chain below:

base_delivery_carrier_label -> delivery_carrier_info -> delivery -> sale_stock ->stock_account -> [ stock ]

2022-07-04 11:16 UTC, KKamaa commented
@OCA/community-maintainers can someone do a check on this please

2022-11-14 23:21 UTC, KKamaa commented
@thomaspaulb we are currently using this in our own 14.0 migration its labelled as stale

2022-11-15 08:18 UTC, sebalix commented
@KKamaa Hello, we didn't saw your PR this year (the title was skipping the `_` in the name of the module so we didn't find it), so we did this one earlier this year: https://github.com/OCA/delivery-carrier/pull/456

I compared both migration commits and there are quite some changes between them, I can't say which one is better. What I know is we are using the linked PR above in production for some months now without issues, can you have a look at it please?

2022-11-15 08:32 UTC, sebalix commented
@sonhd91 Can you have a look on this one too?

2023-04-30 12:24 UTC, closed without merging