[FIX] base_delivery_carrier_label: avoid duplicating carrier_id
OCA/delivery-carrier pull request #488
Opened 2022-05-21 13:14 UTC by hailangvn

This is to remove duplicated carrier_id.

2022-05-25 13:20 UTC, sebalix requested changes

2022-05-25 13:20 UTC, sebalix commented on base_delivery_carrier_label/views/stock.xml
>          <field name="inherit_id" ref="stock.vpicktree" />
As `carrier_id` doesn't exist in `stock.vpicktree`, you should inherit `delivery.vpicktree_view_tree` instead.
EDIT: I don't know why Travis/Runboat doesn't fail on that, we got the error locally when testing :thinking: 
EDIT 2: it is triggered when we install/update another addon updating the `stock.picking` tree view, and when Odoo tries to apply all the inherited views it fails. The installation/update of `base_delivery_carrier_label` works well on itself even if there is an issue.

2022-05-26 01:12 UTC, hailangvn commented on base_delivery_carrier_label/views/stock.xml
>          <field name="inherit_id" ref="stock.vpicktree" />
Thanks @sebalix for your review. The view does correctly inherit `delivery.vpicktree_view_tree` now.

2022-05-26 05:54 UTC, sebalix approved these changes

2022-05-27 14:38 UTC, sebalix commented
/ocabot merge minor

2022-05-27 14:46 UTC, merged