[15.0][MIG] stock_picking_delivery_link
OCA/delivery-carrier pull request #532
Opened 2022-09-28 15:01 UTC by flachica

2022-09-29 08:23 UTC, victoralmau requested changes

2022-09-29 08:23 UTC, victoralmau commented on stock_picking_delivery_link/tests/common.py
> +class StockPickingDeliveryLinkCommonCase(SavepointCase):
```suggestion
from odoo.tests import TransactionCase


class StockPickingDeliveryLinkCommonCase(TransactionCase):
```

2022-09-29 08:23 UTC, victoralmau commented on stock_picking_delivery_link/tests/common.py
> +        move.onchange_product_id()
```suggestion
        move._onchange_product_id()
```

2022-09-29 10:31 UTC, flachica commented
Thanks @victoralmau I was distracted. I am doing a migration of a module with many dependencies and I am gradually checking

2022-09-29 14:12 UTC, victoralmau approved these changes
Code review OK (although I have never used this module).

2022-10-10 13:18 UTC, rousseldenis commented
/ocabot migration stock_picking_delivery_link

2022-10-10 13:19 UTC, rousseldenis approved these changes
Code review

2022-10-10 15:02 UTC, rousseldenis commented
/ocabot merge patch

2022-10-10 15:08 UTC, merged