[14.0][ADD] delivery_line_qty_delivered
OCA/delivery-carrier pull request #576
Opened 2022-12-11 14:25 UTC by mt-software-de

This modules changes the Delivered Quantity (qty_delivered) of a delivery sale.order.line
if one other sale.order.line is delivered
the qty_deliverd of the delvivery line is changed to its Quantity (product_uom_qty)",

2022-12-12 07:26 UTC, jbaudoux commented on delivery_line_qty_delivered/__manifest__.py
> +    "if one other sale.order.line is delivered the qty_deliverd of the delvivery line"
```suggestion
    "if one other sale.order.line is delivered the qty_delivered of the delivery line"
```

2022-12-12 07:32 UTC, jbaudoux commented on delivery_line_qty_delivered/models/sale_order_line.py
> +                line.qty_delivered = line.product_uom_qty
I would put that in a method `_get_delivery_qty_delivered()` as some may want a different value

2022-12-12 07:53 UTC, jbaudoux commented on delivery_line_qty_delivered/models/sale_order_line.py
> +        for line in self.filtered(lambda sol: sol.qty_delivered_method == "delivery"):
Put the check inside the loop to prevent double loop

2022-12-12 08:00 UTC, jbaudoux requested changes
The dependencies seems to cause a non deterministic result

2022-12-12 08:00 UTC, jbaudoux commented on delivery_line_qty_delivered/models/sale_order_line.py
> +        "order_id.delivery_state",
I think you should not add this depend otherwise you are creating a dependency loop between `_compute_qty_delivered` and `_compute_sale_delivery_state`

2022-12-12 08:00 UTC, jbaudoux commented on delivery_line_qty_delivered/models/sale_order.py
> +                sale.modified(["delivery_state"])
Have you tried flagging `qty_delivered_manual` as modified instead?

2022-12-12 08:29 UTC, mt-software-de commented on delivery_line_qty_delivered/models/sale_order_line.py
> +        "order_id.delivery_state",
Yes i know, but what i need is a dependency on each other line's qty_delivered

2022-12-12 08:32 UTC, mt-software-de commented on delivery_line_qty_delivered/models/sale_order_line.py
> +        "order_id.delivery_state",
What i can do is removing the dependency completely, and trigger the computation from sale.order

2023-02-05 19:59 UTC, mt-software-de commented
> The dependencies seems to cause a non deterministic result

I removed the dependency. 
@jbaudoux  or @rousseldenis could you maybe have a look at tests?
Because the tests are running locally.

2023-07-25 07:19 UTC, rousseldenis commented
/ocabot rebase

2023-07-25 07:30 UTC, rousseldenis commented
@mt-software-de I would try to install all the modules installed before this one (see log details) and see which one is modifying standard behavior.

2023-07-25 07:38 UTC, mt-software-de commented
> @mt-software-de I would try to install all the modules installed before this one (see log details) and see which one is modifying standard behavior.

Thxs, Unfortunately I have to do that.

2023-10-13 18:32 UTC, mt-software-de commented
This was now moved to https://github.com/OCA/sale-workflow/pull/2717

2023-10-13 18:32 UTC, closed without merging