[13.0][IMP] delivery_state: new state to ignore further update calls
OCA/delivery-carrier pull request #579
Opened 2022-12-12 16:15 UTC by chienandalu

It could happen that a carrier deletes tracking numbers from its DB and those states are not longer updatable. We don't want to be checking them forever, so we want a state to ignore them in the future.

cc @Tecnativa TT40774

2022-12-12 17:52 UTC, pedrobaeza requested changes
I think this shouldn't be handled as state level, but an extra boolean flag for that, for not losing last state tracked.

And on the update cron, if an error is raised, to mark such flag.

And finally another thing that I'm remembering now: on the log, all the state are repeated each time a new one is got. Can this be avoided?

2022-12-14 08:10 UTC, chienandalu commented
> I think this shouldn't be handled as state level, but an extra boolean flag for that, for not losing last state tracked. And on the update cron, if an error is raised, to mark such flag.

For the case presented, there's no exception. Just a message reporting that the tracking number doesn't exists. But if we were to flag the pickings which delivery state update ends in an exception (e. g.: temporary API failures), we could be flagging wrongly those.

> And finally another thing that I'm remembering now: on the log, all the state are repeated each time a new one is got. Can this be avoided?

That's formatted for every carrier request class. This module only adds the method plugs.

2022-12-14 08:17 UTC, pedrobaeza approved these changes
OK, let's go this way.

2022-12-14 08:17 UTC, victoralmau approved these changes

2022-12-14 08:19 UTC, pedrobaeza commented
/ocabot merge patch

2022-12-14 10:15 UTC, pedrobaeza commented
/ocabot merge patch

2022-12-14 10:30 UTC, merged