15.0 mig delivery carrier category
OCA/delivery-carrier pull request #602
Opened 2023-01-19 06:33 UTC by pere-aquarian

2023-01-19 16:39 UTC, rousseldenis commented
/ocabot migration delivery_carrier_category

2023-01-19 16:46 UTC, rousseldenis requested changes
@pere-aquarian Thanks for this.

Could you attend comment and as module exists in v14, migrate from that one.

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

2023-01-19 16:46 UTC, rousseldenis commented on delivery_carrier_category/security/delivery_carrier_category.xml
> +    <record model="ir.rule" id="delivery_carrier_category_salesman">
@pere-aquarian You cannot do that!

Please restore ir.model.access model.

See: 
![image](https://user-images.githubusercontent.com/19529533/213503728-22812a13-a189-42e7-b96d-fa4a5bfb2d37.png)

2023-01-25 11:56 UTC, pere-aquarian commented on delivery_carrier_category/security/delivery_carrier_category.xml
> +    <record model="ir.rule" id="delivery_carrier_category_salesman">
done! @rousseldenis

2023-01-25 15:18 UTC, rousseldenis requested changes
Could you change test class to TransactionCase and squash your commits to keep migration one ? Thanks

2023-01-25 15:18 UTC, rousseldenis commented on delivery_carrier_category/tests/test_carrier_category.py
> +class TestCarrierCategory(SavepointCase):
```suggestion
class TestCarrierCategory(TransactionCase):
```

2023-02-03 11:49 UTC, pere-aquarian commented on delivery_carrier_category/tests/test_carrier_category.py
> +class TestCarrierCategory(SavepointCase):
Done!

2023-02-06 05:05 UTC, pere-aquarian commented
Thank you for the patience, @rousseldenis . Just a rookie on that and I am starting from the easiest modules to understand the whole process. Think I am done. Commits squashed and only one left with the migration one.

2023-02-06 08:01 UTC, rousseldenis commented
> Thank you for the patience, @rousseldenis . Just a rookie on that and I am starting from the easiest modules to understand the whole process. Think I am done. Commits squashed and only one left with the migration one.

@pere-aquarian No problem, always a pleasure to welcome new people contributing ! I'll try to look at it today

2023-02-14 05:53 UTC, pere-aquarian commented
@jcbr87 Could you please take a look at it? 
Thank you!

2023-07-19 22:42 UTC, pere-aquarian commented
Hi, @rousseldenis !

Is there something more I have to do? Sorry my ignorance.

Thank you!

2023-07-20 06:06 UTC, rousseldenis commented
@pere-aquarian It seems your commit history is quite a mess as there is another module in it.

Did you follow the migration guide I've provided here above (especially the Full process part) ?

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

2023-12-31 12:24 UTC, closed without merging