[16.0][MIG] delivery_carrier_service_level: Migration to 16.0
OCA/delivery-carrier pull request #607
Opened 2023-02-07 13:55 UTC by ntsirintanis

Standard migration.

2023-02-17 11:02 UTC, rousseldenis commented
/ocabot migration delivery_carrier_service_level

2023-02-17 11:03 UTC, rousseldenis commented
@ntsirintanis Could you fix pre-commit ?

2023-02-17 11:05 UTC, rousseldenis commented on .pre-commit-config.yaml
> +    rev: 5.12.0
@ntsirintanis And could you rebase and remove this ?

2023-02-17 11:39 UTC, ntsirintanis commented
@rousseldenis I did the changes, revert isort back to version 5.10.1, and now that's the reason that pre-commit fails. How can I amend that?

2023-02-17 11:52 UTC, rousseldenis commented on .pre-commit-config.yaml
> +    rev: 5.10.1
I wanted to say you can remove that change as it is already in 16 branch 😅

2023-07-25 07:12 UTC, rousseldenis requested changes

2023-07-25 07:12 UTC, rousseldenis commented on delivery_carrier_service_level/__manifest__.py
> +    "version": "16.0.1.0.2",
Please reset this to 16.0.1.0.0

2023-07-25 07:12 UTC, rousseldenis commented on delivery_carrier_service_level/models/stock_picking.py
> +    carrier_service_level_id = fields.Many2one(
Please put field definition on top

2023-07-25 09:34 UTC, rousseldenis approved these changes
Code review

2023-08-27 12:22 UTC, closed without merging