[16.0][MIG] carrier_account_environment
OCA/delivery-carrier pull request #616
Opened 2023-03-07 23:10 UTC by florian-dacosta

Standart migration

2023-03-10 10:15 UTC, hparfr requested changes

2023-03-10 10:15 UTC, hparfr commented on carrier_account_environment/readme/CONFIGURE.rst
> +configured in the `server_environment_files` module (which is a module
can you also talk about the alternatives like [server_environment_data_encryption](https://github.com/OCA/server-env/tree/14.0/server_environment_data_encryption)

2023-07-25 07:08 UTC, rousseldenis commented
/ocabot migration carrier_account_environment

2023-07-25 07:09 UTC, rousseldenis approved these changes
Code review

2023-09-27 12:24 UTC, bguillot approved these changes

2023-10-03 11:17 UTC, florian-dacosta commented
@hparfr If you are ok with the README change, can you merge the PR please?

2023-10-03 12:03 UTC, hparfr approved these changes
/ocabot merge nobump

2023-10-03 12:11 UTC, merged