[16.0][ADD] delivery_package_automatic
OCA/delivery-carrier pull request #642
Opened 2023-05-23 13:12 UTC by rousseldenis

2023-05-23 15:40 UTC, lmignon commented on delivery_package_automatic/models/res_company.py
> +    automatic_package_creation_default = fields.Boolean(
s/automatic_package_creation_default/automatic_package_creation_at_delivery_default

2023-05-23 15:40 UTC, lmignon commented on delivery_package_automatic/models/res_config_settings.py
> +    automatic_package_creation_default = fields.Boolean(
s/automatic_package_creation_default/automatic_package_creation_at_delivery_default

2023-05-23 15:43 UTC, lmignon requested changes
LGTM but a more would use a field name that better reflect the context where it's used.

2023-05-24 08:05 UTC, rousseldenis commented on delivery_package_automatic/models/res_company.py
> +    automatic_package_creation_default = fields.Boolean(
Done

2023-05-24 08:06 UTC, rousseldenis commented on delivery_package_automatic/models/res_config_settings.py
> +    automatic_package_creation_default = fields.Boolean(
Done

2023-05-24 08:46 UTC, bealdav commented on delivery_automatic_package/models/delivery_carrier.py
> +    automatic_package_creation_at_delivery = fields.Boolean(
Nitpicking
Python code makes things automatic, then `automatic`  have no high value here and make field name longer useless.
```suggestion
    package_creation_at_delivery = fields.Boolean(
```

2023-05-24 08:54 UTC, rousseldenis commented on delivery_automatic_package/models/delivery_carrier.py
> +    automatic_package_creation_at_delivery = fields.Boolean(
Yes, but that reflects a change from standard behavior.

Apart that, are you ok with the change ?

2023-05-24 08:54 UTC, lmignon approved these changes
LGTM (Code review)

2023-05-25 09:59 UTC, bealdav approved these changes
Thanks a lot for this contribution, LGTM code review.

My own preference is to have only meaningful words in fields to make it shorter, but that's just my taste.

Then that's an unconditionally approve

2023-05-31 12:40 UTC, florian-dacosta approved these changes
Thanks a lot for this PR, I think it is a very good thing to make this feature in a separate module so it becomes optional.
LGTM code review

2023-05-31 13:13 UTC, bguillot commented
/ocabot merge nobump

2023-05-31 13:14 UTC, bguillot commented
Thanks @rousseldenis !

2023-05-31 13:21 UTC, merged