[ADD] Adjust Submit booking due to schenker delivery carrier options
OCA/delivery-carrier pull request #723
Opened 2023-10-25 09:24 UTC by vnikolayev1

- Added field for schenker delivery carrier, where user can pick if they want to submit booking on schenker site. In case where it is turned off - user has to submit booking manually.

2023-10-26 19:58 UTC, mt-software-de requested changes
Thanks for contributing

2023-10-26 19:58 UTC, mt-software-de commented on delivery_schenker/models/delivery_carrier.py
> +                "submitBooking": picking.carrier_id.is_schenker_submit_booking,
```suggestion
                "submitBooking": self.is_schenker_submit_booking,
```

2023-10-26 19:58 UTC, mt-software-de commented on delivery_schenker/models/delivery_carrier.py
> +    )
Could you please change the name of the field to schenker_submit_booking
```suggestion
    schenker_submit_booking = fields.Boolean(
        string="Submit Booking",
        default=True,
        help="Submit Booking On Schenker site."
        "\nIf set, submits booking on site automatically."
        "\nIf not set, user has to submit booking manually.",
    )
```

2023-10-26 19:58 UTC, mt-software-de commented on delivery_schenker/__manifest__.py
> +    "version": "14.0.1.2.1",
Please remove this change. This should be automatically done by the merge bot.

2023-10-26 19:58 UTC, mt-software-de commented on delivery_schenker/tests/common.py
> +        )
What is the purpose of this change?

2023-12-11 14:54 UTC, jbaudoux approved these changes
LGTM, not tested

2023-12-11 14:56 UTC, jbaudoux commented
@vnikolayev1 Can you rebase and repush as pre-commit failed

2024-03-20 09:44 UTC, vnikolayev1 commented
@jbaudoux sorry for delay, should be good now

2024-03-20 09:45 UTC, mt-software-de commented
> @jbaudoux sorry for delay, should be good now

Please rebase and not merge. To get rid of the second commit.

2024-03-20 12:05 UTC, mt-software-de approved these changes

2024-03-20 13:37 UTC, jbaudoux commented
/ocabot merge minor

2024-03-20 13:47 UTC, merged