[16.0][ADD] delivery_driver_stock_picking_batch
OCA/delivery-carrier pull request #759
Opened 2024-01-08 09:10 UTC by EmilioPascual

Add drivers in stock picking batch

PR Series: https://github.com/OCA/delivery-carrier/pull/752 (must be merged before this one)

@Shide @gelojr @rafaelbn please review.

MT-4427 @moduon

2024-01-10 10:53 UTC, Shide requested changes
Good job!

**suggestion**: Add the same domain as the stock.picking

2024-01-10 10:53 UTC, Shide commented on delivery_driver_stock_picking_batch/models/stock_picking_batch.py
> +        "res.partner", string="Drivers", compute="_compute_driver_ids", store=True
Add the same domain as the stock.picking

```suggestion
        "res.partner", string="Drivers", compute="_compute_driver_ids", store=True, domain="[('is_company', '=', False)]",
```

2024-01-15 15:22 UTC, EmilioPascual commented on delivery_driver_stock_picking_batch/models/stock_picking_batch.py
> +        "res.partner", string="Drivers", compute="_compute_driver_ids", store=True
Done. Thanks.

2024-01-15 15:35 UTC, fcvalgar approved these changes

2024-01-15 15:42 UTC, EmilioPascual commented
https://www.loom.com/share/c53127a53b664a06b2e81c026a27cf88

2024-01-16 09:51 UTC, fcvalgar approved these changes
LGTM, thank you @EmilioPascual 

![image](https://github.com/OCA/delivery-carrier/assets/17847432/7f903445-164d-475f-9994-a74ae99a601b)

![image](https://github.com/OCA/delivery-carrier/assets/17847432/52e0d34b-feb5-4e98-8d29-4c313b8e26fe)

![image](https://github.com/OCA/delivery-carrier/assets/17847432/8d6c1b90-769a-4b83-bbe0-408207db58b5)


![image](https://github.com/OCA/delivery-carrier/assets/17847432/f7ad77a8-45b2-4de7-bb51-4d034de2e3e8)

2024-01-17 10:35 UTC, Shide approved these changes

2024-01-26 12:00 UTC, Gelojr approved these changes
Nice job @EmilioPascual 
LGTM https://www.loom.com/share/a5520ca5fa7f4667be40aa535b40bbf2?sid=1187a7c8-a2a2-42e5-a08f-a252b0f64f7c

2024-01-31 10:20 UTC, EmilioPascual commented
@rafaelbn can you review and merge if neccesary?

2024-02-01 15:09 UTC, rafaelbn approved these changes
Great. thank you! 👍🏼 

/ocabot merge patch

2024-02-02 14:54 UTC, EmilioPascual commented
@rafaelbn I made rebase, please try again 🙏🏻

2024-02-02 20:33 UTC, rafaelbn commented
/ocabot merge patch

2024-02-02 20:40 UTC, merged