[16.0][ADD] delivery_carrier_manual_weight
OCA/delivery-carrier pull request #760
Opened 2024-01-08 14:49 UTC by JordiMForgeFlow

2024-01-11 11:27 UTC, PauBForgeFlow approved these changes
Functional review! LGTM!

2024-05-21 09:36 UTC, AaronHForgeFlow approved these changes
Code review LGTM

2024-09-30 06:41 UTC, JordiMForgeFlow commented
Hi @rousseldenis, could we get a review and merge on this one? :)

2024-10-01 10:27 UTC, rousseldenis requested changes
Looks great.

One important change

2024-10-01 10:27 UTC, rousseldenis commented on delivery_carrier_manual_weight/models/stock_picking.py
> +        "move_ids", "carrier_id", "carrier_id.is_manual_weight", "weight_manual"
You cannot do that as if configuration changes, every picking will be recomputed.

```suggestion
        "move_ids", "carrier_id", "weight_manual"
```

2024-10-01 10:27 UTC, rousseldenis commented on delivery_carrier_manual_weight/models/stock_picking.py
> +        "carrier_id.is_manual_weight",
Same as above

2024-10-01 10:51 UTC, JordiMForgeFlow commented
totally agree @rousseldenis , thank you! :) It is changed now

2024-10-01 10:56 UTC, rousseldenis approved these changes

2024-10-01 10:56 UTC, rousseldenis commented
/ocabot merge nobump

2024-10-01 11:03 UTC, merged