[17.0][MIG] delivery_carrier_info
OCA/delivery-carrier pull request #779
Opened 2024-03-07 14:32 UTC by AndreuOForgeFlow

Standard Migration

@ForgeFlow

2024-03-07 15:04 UTC, GuillemCForgeFlow requested changes

2024-03-07 15:04 UTC, GuillemCForgeFlow commented on delivery_carrier_info/migrations/16.0.1.0.0/pre-migration.py
> +            )
```suggestion
```
When migrating to the new version, we need to remove the migration files from the previous one. We just need to add some, if they are needed for the migration to v17, in this case.

2024-03-07 15:22 UTC, GuillemCForgeFlow approved these changes
LGTM! Code and functional review 👍🏽

2024-03-12 09:53 UTC, rousseldenis commented
/ocabot migration delivery_carrier_info

2024-03-12 09:55 UTC, rousseldenis approved these changes
Code review.

I know this has been discussed but I'm wondering if this deserves a base module to add a group in forms and then add 'code' and so on...

@florian-dacosta

2024-05-02 13:54 UTC, dreispt commented
/ocabot merge nobump

2024-05-02 13:59 UTC, merged