[16.0] [MIG] delivery_roulier_option
OCA/delivery-carrier pull request #837
Opened 2024-06-20 21:01 UTC by chafique-delli

2024-07-04 11:52 UTC, hparfr requested changes

2024-07-04 11:52 UTC, hparfr commented on delivery_roulier_option/models/stock_quant_package.py
> -                    % (product.display_name, product.categ_id.display_name)
are you sure about this change ?

2024-07-09 09:39 UTC, hparfr approved these changes

2024-07-09 09:40 UTC, florian-dacosta approved these changes

2024-07-09 09:42 UTC, hparfr commented
/ocabot migration

2024-07-09 09:42 UTC, hparfr commented
/ocabot migration delivery_roulier_option

2024-07-09 09:43 UTC, hparfr commented
/ocabot merge nobump

2024-07-09 09:50 UTC, merged